### Links:
* https://pages.uoregon.edu/sanjay/pubs/bigfive.pdf - paper on 44-question BFI
* https://en.wikipedia.org/wiki/Big_Five_personality_traits - Wikipedia on Big-5
* https://fetzer.org/sites/default/files/images/stories/pdf/selfmeasures/Personality-BigFiveInventory.pdf - 44-question BFI
* https://pages.uoregon.edu/sanjay/bigfive.html#where
* https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4748047/ - abusive boss paper, classified by big-5
* https://drive.google.com/file/d/1bbbn8kSBmcVObafdzAQEipRBc4SVqwtb/view - essays dataset
* https://betterprogramming.pub/beginners-to-advanced-feature-engineering-from-text-data-c228047a4813 - feature engineering from text

In [87]:
import numpy as np
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)
pd.set_option('display.width', 1000)

In [5]:
df = pd.read_csv("messages.csv")
df

Unnamed: 0        _     id                                         peer_id                       date                                            message    out  mentioned  media_unread  silent   post from_scheduled  legacy edit_hide pinned                                   from_id fwd_from  via_bot_id                                           reply_to                                              media  reply_markup                                           entities  views  forwards                                            replies                  edit_date  post_author  grouped_id restriction_reason  ttl_period   sender_id  sender_username action
0              0  Message  21389  {'_': 'PeerChannel', 'channel_id': 1121514187}  2022-08-03 10:39:17+00:00  Запрет-то только на афроарабомигрантов, которы...  False      False         False   False  False          False   False     False  False  {'_': 'PeerUser', 'user_id': 1270290491}      NaN         NaN  {'_': 'MessageReplyHeader', 'reply_to_msg_id':...  {'_': 'MessageMediaWebPage', 'webpage': {'_': ...           NaN  [{'_': 'MessageEntityUrl', 'offset': 157, 'len...    NaN       NaN                                                NaN  2022-08-03 10:40:34+00:00          NaN         NaN                 []         NaN  1270290491         vladdotx    NaN
1              1  Message  21388  {'_': 'PeerChannel', 'channel_id': 1121514187}  2022-08-03 10:37:55+00:00  это понятно, меня интересует, как они собирают...  False      False         False   False  False          False   False     False  False    {'_': 'PeerUser', 'user_id': 83318143}      NaN         NaN  {'_': 'MessageReplyHeader', 'reply_to_msg_id':...                                                NaN           NaN                                                 []    NaN       NaN                                                NaN                        NaN          NaN         NaN                 []         NaN    83318143  quetzal_rainbow    NaN
2              2  Message  21387  {'_': 'PeerChannel', 'channel_id': 1121514187}  2022-08-03 10:37:49+00:00  Орбан опять же не вечный, идиократия на следую...  False      False         False   False  False          False   False     False  False  {'_': 'PeerUser', 'user_id': 1270290491}      NaN         NaN                                                NaN                                                NaN           NaN                                                 []    NaN       NaN  {'_': 'MessageReplies', 'replies': 0, 'replies...                        NaN          NaN         NaN                 []         NaN  1270290491         vladdotx    NaN
3              3  Message  21386  {'_': 'PeerChannel', 'channel_id': 1121514187}  2022-08-03 10:35:38+00:00  высококвалифицированным специалистам лучше еха...  False      False         False   False  False          False   False     False  False  {'_': 'PeerUser', 'user_id': 1270290491}      NaN         NaN  {'_': 'MessageReplyHeader', 'reply_to_msg_id':...                                                NaN           NaN                                                 []    NaN       NaN                                                NaN                        NaN          NaN         NaN                 []         NaN  1270290491         vladdotx    NaN
4              4  Message  21385  {'_': 'PeerChannel', 'channel_id': 1121514187}  2022-08-03 10:34:57+00:00  интересно, а какие условия миграции в Венгрию ...  False      False         False   False  False          False   False     False  False    {'_': 'PeerUser', 'user_id': 83318143}      NaN         NaN  {'_': 'MessageReplyHeader', 'reply_to_msg_id':...                                                NaN           NaN                                                 []    NaN       NaN                                                NaN                        NaN          NaN         NaN                 []         NaN    83318143  quetzal_rainbow    NaN
...          ...      ...   

In [8]:
df.groupby(['sender_username'])['sender_username'].count().sort_values(ascending=False)

sender_username
BurkovBA                3070
Oleg_Solovyov           1187
vladdotx                 596
arzvael                  477
chaotic88chaotic         468
Ts1Nik                   351
quetzal_rainbow          338
olegkovale               280
ozolotareva              270
g00dwin2003              232
dmitryvim                195
ilmir                    186
denis_shepelin           167
BorisBurkov              149
belichie                 129
st_ts42                  121
igor_bn                  114
tetrapotmelontea         104
winddevofficer            89
sasha_sturdy              79
host2035                  75
DaveBrubeck               71
E_caterinaR               61
atropos                   53
svevol                    51
AndreiKei                 49
cloud_tg_captcha_bot      49
makartnipol               44
addver                    39
Mobideer                  37
Ba_Si_Li                  28
ttimurshin                23
bomjasov                  23
rkoltykov                 2

In [50]:
essays = pd.read_csv("essays.csv")
essays.loc[essays['cEXT'] == 'n', 'cEXT'] = 0
essays.loc[essays['cEXT'] == 'y', 'cEXT'] = 1

essays.loc[essays['cNEU'] == 'n', 'cNEU'] = 0
essays.loc[essays['cNEU'] == 'y', 'cNEU'] = 1

essays.loc[essays['cAGR'] == 'n', 'cAGR'] = 0
essays.loc[essays['cAGR'] == 'y', 'cAGR'] = 1

essays.loc[essays['cCON'] == 'n', 'cCON'] = 0
essays.loc[essays['cCON'] == 'y', 'cCON'] = 1

essays.loc[essays['cOPN'] == 'n', 'cOPN'] = 0
essays.loc[essays['cOPN'] == 'y', 'cOPN'] = 1

essays

#AUTHID                                               TEXT cEXT cNEU cAGR cCON cOPN
0     1997_504851.txt  Well, right now I just woke up from a mid-day ...    0    1    1    0    1
1     1997_605191.txt  Well, here we go with the stream of consciousn...    0    0    1    0    0
2     1997_687252.txt  An open keyboard and buttons to push. The thin...    0    1    0    1    1
3     1997_568848.txt  I can't believe it!  It's really happening!  M...    1    0    1    1    0
4     1997_688160.txt  Well, here I go with the good old stream of co...    1    0    1    0    1
...               ...                                                ...  ...  ...  ...  ...  ...
2462     2004_493.txt       I'm home. wanted to go to bed but remembe...    0    1    0    1    0
2463     2004_494.txt       Stream of consiousnesssskdj. How do you s...    1    1    0    0    1
2464     2004_497.txt  It is Wednesday, December 8th and a lot has be...    0    0    1    0    0
2465     2004_498.txt  Man this week has been hellish. Anyways, now i...    0    1    0    0    1
2466     2004_499.txt  I have just gotten off the phone with brady. I...    0    1    1    0    1

[2467 rows x 7 columns]

In [81]:
import gensim


corpus = essays['TEXT'].to_list()

def read_corpus(corpus, tokens_only=False):
    for index, document in enumerate(corpus):
        preprocessed_document = gensim.utils.simple_preprocess(document)
        corpus[index] = preprocessed_document

        if tokens_only:
            yield preprocessed_document
        else:
            # For training data, add tags
            yield gensim.models.doc2vec.TaggedDocument(preprocessed_document, [index])

train_corpus = list(read_corpus(corpus[:2000]))
train_corpus_tokens_only = list(read_corpus(corpus[:2000], tokens_only=True))
test_corpus = list(read_corpus(corpus[2000:], tokens_only=True))

In [82]:
model = gensim.models.doc2vec.Doc2Vec(vector_size=50, min_count=2, epochs=40)

model.build_vocab(train_corpus)

model.train(
    train_corpus, 
    total_examples=model.corpus_count, 
    epochs=model.epochs
)

In [68]:
# model = gensim.models.FastText(vector_size=100)

# model.train(
#     corpus_iterable=corpus,
#     epochs=model.epochs,
#     total_examples=model.corpus_count,
#     total_words=model.corpus_total_words,
# )

# model.wv.most_similar("hopefully")

In [119]:
X_train = np.array([model.infer_vector(train_corpus_tokens_only[0])])

for document in train_corpus_tokens_only[1:]:
    row = model.infer_vector(document)
    X_train = np.append(X_train, [row], axis=0)

In [120]:
y_train = essays['cNEU'][:2000].to_numpy()
y_train = y_train.astype('int')

In [121]:
X_test = np.array([model.infer_vector(test_corpus[0])])

for document in test_corpus[1:]:
    row = model.infer_vector(document)
    X_test = np.append(X_test, [row], axis=0)

In [122]:
y_test = essays['cNEU'][2000:].to_numpy()
y_test = y_test.astype('int')

In [123]:
from sklearn.linear_model import LogisticRegression


logreg = LogisticRegression()
logreg.fit(X_train, y_train)
y_test_pred = logreg.predict_proba(X_test)
logreg.score(X_test, y_test)

0.5331905781584583

In [124]:
for i in zip(y_test_pred, y_test):
    print(i)

(array([0.59761436, 0.40238564]), 0)
(array([0.52072577, 0.47927423]), 1)
(array([0.67575946, 0.32424054]), 1)
(array([0.2951286, 0.7048714]), 0)
(array([0.33053986, 0.66946014]), 0)
(array([0.55073057, 0.44926943]), 1)
(array([0.52060693, 0.47939307]), 0)
(array([0.53214786, 0.46785214]), 1)
(array([0.69786022, 0.30213978]), 1)
(array([0.61998819, 0.38001181]), 0)
(array([0.4624882, 0.5375118]), 1)
(array([0.42535374, 0.57464626]), 1)
(array([0.28912154, 0.71087846]), 0)
(array([0.49363806, 0.50636194]), 0)
(array([0.63796492, 0.36203508]), 1)
(array([0.40275607, 0.59724393]), 1)
(array([0.73656284, 0.26343716]), 0)
(array([0.42062412, 0.57937588]), 0)
(array([0.3643525, 0.6356475]), 1)
(array([0.69340307, 0.30659693]), 0)
(array([0.44330484, 0.55669516]), 1)
(array([0.57328412, 0.42671588]), 1)
(array([0.59768163, 0.40231837]), 1)
(array([0.60557756, 0.39442244]), 1)
(array([0.74998311, 0.25001689]), 0)
(array([0.35678187, 0.64321813]), 0)
(array([0.38708304, 0.61291696]), 1)
(array(

In [136]:
essays.loc[4]
# essays['TEXT'][4]

#AUTHID                                      1997_688160.txt
TEXT       Well, here I go with the good old stream of co...
cEXT                                                       1
cNEU                                                       0
cAGR                                                       1
cCON                                                       0
cOPN                                                       1
Name: 4, dtype: object